version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password # Set the root password
      MYSQL_DATABASE: bakariDB # Create a default database
      MYSQL_USER: faiz # Create a non-root user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
